### PR TITLE
handle get requests

### PR DESCRIPTION
**Pull request by uhbrar**
Handles get requests for endpoints that do not accept post requests

### CODE REVIEW

**Review by maximusunc — COMMENTED** [review]
I think the implementation is fine, but I'm a little confused why we go about it this way. It looks like you're just making sure the endpoint accepts POST and if it doesn't then we send a GET request. Why not just make the test specify if it's a GET request? I think we want to follow what the test wants as close as possible and not change what type of request we send based on the external service. Let me know if this is way off base.

**Comment by uhbrar** [comment]
I actually think that's a much better implementation, but then we'd need to have the tests specify using a GET request. I still think having it default to a POST makes sense, so if the test doesn't specify which method to use, we send a POST request. If the test does specify a method to use though, then we can just use whatever it tells us to use. In that case, I guess we would need to make an issue in the testing repo?

**Comment by maximusunc** [comment]
I agree, use whatever the test specifies with a default fallback POST. I'm not sure the tests repo needs an issue as there's no schema to change, people will just need to update their tests if they want.

**Comment by uhbrar** [comment]
Wouldn't it require a schema change? With the current format, there's no way to specify desired method on a test json. I don't want to just make that decision on my own.

**Review by maximusunc — APPROVED** [review]

**Pull request merged**
